services:
  backend:
    image: ${ECR_REPOSITORY_URL}:${IMAGE_TAG}
    container_name: allrecords-backend
    restart: always
    env_file:
      - app.env
      - deploy.env
    ports:
      - "127.0.0.1:3000:3000"
